# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_CONFIGURATION: 'Release'                                                      
  DOTNET_VERSION: '8.0.x' 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: dotnet build and test
      run: |
        dotnet restore
        dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}'
        dotnet test --configuration '${{ env.BUILD_CONFIGURATION }}'
          
