# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_CONFIGURATION: 'Release'                                                      
  DOTNET_VERSION: '8.0.x' 
  GITHUB_PACKAGE_REGISTRY_URL: https://nuget.pkg.github.com/Nathallia/index.json
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: dotnet build and test
      run: |
        dotnet restore
        dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}'
        dotnet test --configuration '${{ env.BUILD_CONFIGURATION }}'
  deploy-pkg:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.GITHUB_PACKAGE_REGISTRY_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Run dotnet build and package
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}'
          dotnet pack -c '${{ env.BUILD_CONFIGURATION }}'
          
      # Publish the package to GitHub Package Registry
      - name: 'dotnet publish'
        run: dotnet nuget push LibreriaNet/bin/Release/*.nupkg

  
          
